### PR TITLE
finished footer. Added it to other pages

### PR DESCRIPTION
**Pull request by wchipchase**
Completed footer and added it to each page.

### CODE REVIEW

**Comment by GregStephen** [comment]
So the About us page footer looks okay, but the social media links aren't on the brewmaster page, and the contact links aren't on any of them except the about us page.

**Comment by GregStephen** [comment]
Also if you could give the home page title just the id of "pageTitle" that will style it the same as the other pages

**Comment by wchipchase** [comment]
incorporated comments

**Comment by GregStephen** [comment]
👍

**Pull request merged**
